### ISSUE TITLE
Can I have two instances for multi zone?

### ISSUE THREAD

**Issue by iBeech** [dwardu89/hive-trv-appdaemon#7]
More of a question…

I have multizone, can I deploy two instances of this, one for each zone?

I’m looking to move 15 TRVs and 2 zones over to zigbee2mqtt and this automation is pivotal to making the system work.

Thanks for your effort!

**Comment by dwardu89** [comment]
I haven't thought of that, because i only have one zone. but probably in the app config you could set it like this.

```yaml
heating_zone_one:
  module: hive_trv_heating
  class: HiveHeating
  main_thermostat: climate.living_room_thermostat
  main_thermostat_zigbee_set_topic: "zigbee2mqtt/Living Room Thermostat/set"
  trv_list:
    - climate.office_radiator_valve
    - climate.main_bedroom_cove_radiator_valve
    - climate.main_bedroom_radiator_valve
    - climate.hallway_radiator_valve
    - climate.second_bedroom_radiator_valve
  log: heat_log
  trv_boost_mode: input_boolean.trv_heating_boost_mode
  trv_boost_mode_temperature: input_number.trv_boost_mode_temperature
  boost_mode_hold_duration_minutes: 35
heating_zone_two:
  module: hive_trv_heating
  class: HiveHeating
  main_thermostat: climate.living_room_thermostat
  main_thermostat_zigbee_set_topic: "zigbee2mqtt/Living Room Thermostat/set"
  trv_list:
    - climate.office_radiator_valve
    - climate.main_bedroom_cove_radiator_valve
    - climate.main_bedroom_radiator_valve
    - climate.hallway_radiator_valve
    - climate.second_bedroom_radiator_valve
  log: heat_log
  trv_boost_mode: input_boolean.trv_heating_boost_mode
  trv_boost_mode_temperature: input_number.trv_boost_mode_temperature
  boost_mode_hold_duration_minutes: 35
```
